package com.shalako.checkers.model;

import com.shalako.checkers.enums.PieceType;
import com.shalako.checkers.enums.PlayerColor;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Value;

/**
 * Represents a piece in a checkers game.
 */
@Value
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public class Piece {
    PlayerColor color;
    PieceType type;

    /**
     * Promotes this piece to a king if it's a man.
     * Returns a new piece if promotion occurs, otherwise returns this piece.
     */
    public Piece promote() {
        if (type == PieceType.MAN) {
            return new Piece(color, PieceType.KING);
        }
        return this;
    }

    /**
     * Returns a string representation of this piece for display on the board.
     */
    public String getDisplaySymbol() {
        return color.getSymbol() + type.getSymbol();
    }

    // equals, hashCode, and toString are generated by Lombok @Value

    /**
     * Factory for creating pieces.
     */
    public static class PieceFactory {
        /**
         * Creates a new man piece of the specified color.
         */
        public static Piece createMan(PlayerColor color) {
            return new Piece(color, PieceType.MAN);
        }

        /**
         * Creates a new king piece of the specified color.
         */
        public static Piece createKing(PlayerColor color) {
            return new Piece(color, PieceType.KING);
        }
    }
}
